### ISSUE TITLE
vagrant 1.0.1 on ruby-1.9.3-p0 on 32-bit CentOS 5.6 running vagrant-aws-0.0.1

### ISSUE THREAD

**Issue by chewmanfoo** [mlinderm/vagrant-aws#1]
install of vagrant-aws gem went fine.

I'm trying some basic commands and I run into this:

```
$ vagrant
/home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-aws-0.0.1/lib/vagrant-aws/config.rb:5:in `<class:Config>': undefined method `configures' for VagrantAWS::Config:Class (NoMethodError)
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-aws-0.0.1/lib/vagrant-aws/config.rb:4:in `<module:VagrantAWS>'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-aws-0.0.1/lib/vagrant-aws/config.rb:1:in `<top (required)>'
        from /home/jmichael/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/jmichael/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-aws-0.0.1/lib/vagrant-aws.rb:6:in `<top (required)>'
        from /home/jmichael/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:59:in `require'
        from /home/jmichael/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:59:in `rescue in require'
        from /home/jmichael/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-aws-0.0.1/lib/vagrant_init.rb:4:in `<top (required)>'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-1.0.1/lib/vagrant/plugin.rb:68:in `load'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-1.0.1/lib/vagrant/plugin.rb:68:in `block (2 levels) in load!'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-1.0.1/lib/vagrant/plugin.rb:42:in `each'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-1.0.1/lib/vagrant/plugin.rb:42:in `block in load!'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-1.0.1/lib/vagrant/plugin.rb:37:in `each'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-1.0.1/lib/vagrant/plugin.rb:37:in `load!'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-1.0.1/lib/vagrant/environment.rb:514:in `load_plugins'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-1.0.1/lib/vagrant/environment.rb:97:in `initialize'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-1.0.1/bin/vagrant:36:in `new'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/gems/vagrant-1.0.1/bin/vagrant:36:in `<top (required)>'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/bin/vagrant:19:in `load'
        from /home/jmichael/.rvm/gems/ruby-1.9.3-p0@vagrant/bin/vagrant:19:in `<main>'
```

Any ideas?

**Comment by mlinderm** [comment]
I have been away from this for a long time. I will take a look...

**Comment by chewmanfoo** [comment]
If there's anything I can do to help - let me know.

**Comment by mlinderm** [comment]
I started to dig in... Vagrant has changed a lot over the last 9 months or so, and most of this plugin, which is tightly integrated with Vagrant's internals, is broken. It is going to be a pretty extensive rewrite to be operational again. I will try to work on it when I can, but the day job has me pretty maxed out these days...
